import type { NewsSource, RawNewsItem, NewsCategory } from "./types";

const HOUR = 3600 * 1000;

function ago(hours: number): string {
  return new Date(Date.now() - hours * HOUR).toISOString();
}

const SEED: Array<Omit<RawNewsItem, "id" | "publishedAt"> & { hAgo: number }> = [
  // ===== forex (8) =====
  { hAgo: 0.4, sourceLabel: "FinancialJuice", category: "forex", tickers: ["EURUSD", "DXY"],
    titleEn: "ECB officials reiterate data-dependent stance, see no urgency to cut further",
    bodyEn: "Several ECB Governing Council members said Wednesday that the central bank can afford to wait before cutting rates again, citing sticky services inflation and resilient labor data. EURUSD held above 1.0820 after the comments while the dollar index pared early gains.",
    originalUrl: "https://www.financialjuice.com/news/ecb-data-dependent" },
  { hAgo: 1.5, sourceLabel: "Reuters FX", category: "forex", tickers: ["USDJPY", "JPY"],
    titleEn: "Yen jumps as MOF official warns against speculative moves",
    bodyEn: "Japan's top currency diplomat said authorities will respond appropriately to excessive yen weakness, sending USDJPY sharply lower from 154.20 to 153.40 intraday. Markets are now watching for confirmation of intervention in BOJ operations data.",
    originalUrl: "https://www.reuters.com/markets/currencies/yen-mof-warning" },
  { hAgo: 3, sourceLabel: "FinancialJuice", category: "forex", tickers: ["GBPUSD"],
    titleEn: "UK CPI prints hotter than expected, complicates BoE rate path",
    bodyEn: "UK headline CPI came in at 2.4% y/y vs 2.2% expected, with services inflation accelerating to 5.9%. GBPUSD rallied 60 pips and short-end gilt yields jumped, with markets pushing first BoE cut to September.",
    originalUrl: "https://www.financialjuice.com/news/uk-cpi-hotter" },
  { hAgo: 8, sourceLabel: "Bloomberg FX", category: "forex", tickers: ["USDCNH", "CNY"],
    titleEn: "PBoC sets yuan fixing at strongest bias in three months",
    bodyEn: "The People's Bank of China set the daily yuan reference rate notably stronger than market estimates, signaling discomfort with recent depreciation pressure. USDCNH fell 0.4% in offshore trading.",
    originalUrl: "https://www.bloomberg.com/news/pboc-fixing-stronger" },
  { hAgo: 22, sourceLabel: "FinancialJuice", category: "forex", tickers: ["AUDUSD"],
    titleEn: "RBA minutes show board considered both holding and cutting",
    bodyEn: "The Reserve Bank of Australia's August minutes revealed members weighed a 25 bp cut against holding steady, ultimately deciding caution was warranted given still-elevated services inflation. AUDUSD slipped 30 pips on the dovish tilt.",
    originalUrl: "https://www.financialjuice.com/news/rba-minutes" },
  { hAgo: 30, sourceLabel: "Reuters FX", category: "forex", tickers: ["USDCAD"],
    titleEn: "Canadian retail sales miss, BoC cut odds firm",
    bodyEn: "Canada's June retail sales fell 0.3% m/m vs flat expected, with control group also negative. USDCAD broke above 1.3650 as OIS markets priced 80% odds of a BoC cut at the next meeting.",
    originalUrl: "https://www.reuters.com/markets/canada-retail-sales" },
  { hAgo: 50, sourceLabel: "FinancialJuice", category: "forex", tickers: ["USDCHF", "CHF"],
    titleEn: "SNB sight deposits drop, suggesting active FX intervention",
    bodyEn: "Weekly Swiss National Bank sight deposit data showed an unusual 4.2 billion franc decline, fueling speculation the SNB has been selling FX reserves to support the franc. USDCHF traded at three-week lows.",
    originalUrl: "https://www.financialjuice.com/news/snb-sight-deposits" },
  { hAgo: 100, sourceLabel: "Bloomberg FX", category: "forex", tickers: ["EURUSD", "EURGBP"],
    titleEn: "Eurozone PMI surprises to the upside, services lead",
    bodyEn: "Composite eurozone PMI rose to 51.8 from 50.9, with services jumping to 53.1. The data lifted EURUSD 0.5% and tightened EURGBP, supporting the case that the ECB can pause its cutting cycle.",
    originalUrl: "https://www.bloomberg.com/news/eurozone-pmi-beat" },

  // ===== futures (8) =====
  { hAgo: 0.8, sourceLabel: "CME Group", category: "futures", tickers: ["ES", "NQ"],
    titleEn: "S&P 500 futures slip in overnight session as bond yields tick higher",
    bodyEn: "ES futures traded 0.3% lower in the Asian session as 10-year Treasury yields ticked back above 4.30% following stronger-than-expected Australian jobs data. Tech-heavy NQ underperformed, off 0.45%.",
    originalUrl: "https://www.cmegroup.com/markets/equities/sp-overnight" },
  { hAgo: 2, sourceLabel: "FinancialJuice", category: "futures", tickers: ["CL", "BZ"],
    titleEn: "Crude futures spike on unexpected EIA inventory draw",
    bodyEn: "WTI crude futures jumped 2.1% after the EIA reported a 4.6 million barrel inventory drawdown vs expectations of a 1.2 million build. Distillate stocks also fell sharply, supporting the bullish demand narrative.",
    originalUrl: "https://www.financialjuice.com/news/eia-draw-crude" },
  { hAgo: 4, sourceLabel: "Reuters", category: "futures", tickers: ["GC", "SI"],
    titleEn: "Gold futures hit fresh record above $2,560/oz",
    bodyEn: "Comex gold futures broke through resistance to set a new all-time high above $2,560 per ounce, supported by a softer dollar, central bank buying, and positioning ahead of next week's Fed minutes. Silver also rallied 1.8%.",
    originalUrl: "https://www.reuters.com/markets/commodities/gold-record-2560" },
  { hAgo: 9, sourceLabel: "FinancialJuice", category: "futures", tickers: ["NG"],
    titleEn: "Natural gas futures surge as forecasts turn hotter",
    bodyEn: "Henry Hub front-month natural gas futures jumped 5.4% as 6-10 day weather models shifted hotter for the southern US, with cooling demand expected to outpace seasonal norms by ~25%.",
    originalUrl: "https://www.financialjuice.com/news/natgas-hotter-models" },
  { hAgo: 16, sourceLabel: "Reuters", category: "futures", tickers: ["ZC", "ZS", "ZW"],
    titleEn: "Grain complex sells off after USDA boosts yield estimates",
    bodyEn: "CBOT corn futures fell to a four-year low after USDA raised the 2025 corn yield estimate to 183.6 bushels/acre, well above analyst expectations. Soybeans and wheat also closed sharply lower.",
    originalUrl: "https://www.reuters.com/markets/commodities/usda-yields-grains" },
  { hAgo: 28, sourceLabel: "CME Group", category: "futures", tickers: ["ZN", "ZB"],
    titleEn: "Treasury futures fall as Powell signals patience on cuts",
    bodyEn: "10-year and 30-year Treasury futures dropped 0.4% and 0.7% respectively after Fed Chair Powell told Congress the committee can afford to wait for further evidence inflation is sustainably returning to 2% before cutting rates further.",
    originalUrl: "https://www.cmegroup.com/markets/interest-rates/powell-patience" },
  { hAgo: 60, sourceLabel: "FinancialJuice", category: "futures", tickers: ["RB", "HO"],
    titleEn: "RBOB gasoline futures rally on refinery outage",
    bodyEn: "RBOB gasoline futures climbed 3.2% after an unplanned outage at a major Gulf Coast refinery is expected to remove ~280k bpd of capacity for two weeks. Crack spreads widened sharply.",
    originalUrl: "https://www.financialjuice.com/news/refinery-outage-rbob" },
  { hAgo: 110, sourceLabel: "Reuters", category: "futures", tickers: ["HG"],
    titleEn: "Copper futures slide as China property data disappoints",
    bodyEn: "Comex copper futures dropped 1.9% after Chinese property investment fell 10.2% YTD, deepening concerns about industrial metals demand. LME copper also tested its 200-day moving average.",
    originalUrl: "https://www.reuters.com/markets/commodities/copper-china-property" },

  // ===== indices (8) =====
  { hAgo: 0.6, sourceLabel: "FinancialJuice", category: "indices", tickers: ["SPX", "SPY"],
    titleEn: "S&P 500 closes at record high as mega-cap tech extends rally",
    bodyEn: "The S&P 500 ended at a fresh all-time high, lifted by gains in NVIDIA, Microsoft, and Meta. Breadth remained narrow, with the equal-weighted index lagging by 60bps. Volatility continued to compress with VIX printing a sub-13 close.",
    originalUrl: "https://www.financialjuice.com/news/spx-record-close" },
  { hAgo: 2.5, sourceLabel: "Reuters", category: "indices", tickers: ["NDX", "NQ"],
    titleEn: "Nasdaq 100 futures dip overnight on chip sector weakness",
    bodyEn: "NQ futures fell 0.4% in Asia after a major Asian foundry warned of softer auto-chip demand for the second half. ASML and TSMC ADR-equivalents traded lower in pre-market.",
    originalUrl: "https://www.reuters.com/markets/asia/ndx-chip-weakness" },
  { hAgo: 5, sourceLabel: "Bloomberg", category: "indices", tickers: ["DAX"],
    titleEn: "DAX hits new high as German industrial production beats",
    bodyEn: "Germany's DAX index extended its record-setting run, climbing 0.7% to a new closing high. June industrial production rose 1.4% m/m vs 0.5% expected, easing fears of a sustained manufacturing slump.",
    originalUrl: "https://www.bloomberg.com/news/dax-record-german-ip" },
  { hAgo: 11, sourceLabel: "FinancialJuice", category: "indices", tickers: ["RUT", "IWM"],
    titleEn: "Small caps lag as 2-year yields hold above 4.4%",
    bodyEn: "The Russell 2000 underperformed large caps by 90bps as front-end yields held firm following hawkish-leaning Fedspeak. Small-cap rate sensitivity continues to weigh on the index relative to mega-cap leaders.",
    originalUrl: "https://www.financialjuice.com/news/rut-lags-yields" },
  { hAgo: 24, sourceLabel: "Reuters", category: "indices", tickers: ["NIKKEI"],
    titleEn: "Nikkei jumps 2.1% on weak yen, exporter strength",
    bodyEn: "Tokyo's Nikkei 225 rallied 2.1% as a renewed bout of yen weakness lifted exporter shares. Toyota, Sony, and SoftBank all gained more than 2.5%, while bank stocks lagged on softer JGB yields.",
    originalUrl: "https://www.reuters.com/markets/asia/nikkei-exporter-rally" },
  { hAgo: 36, sourceLabel: "Bloomberg", category: "indices", tickers: ["FTSE"],
    titleEn: "FTSE 100 outperforms peers on energy and miner gains",
    bodyEn: "London's FTSE 100 added 0.8% as energy and basic materials sectors led, supported by firmer crude and copper prices. The index continues to benefit from its defensive sector tilt amid renewed European growth concerns.",
    originalUrl: "https://www.bloomberg.com/news/ftse-energy-miners" },
  { hAgo: 70, sourceLabel: "FinancialJuice", category: "indices", tickers: ["HSI"],
    titleEn: "Hang Seng tumbles 1.7% as China stimulus disappoints",
    bodyEn: "Hong Kong's Hang Seng Index slid 1.7% after Chinese officials offered no fresh fiscal stimulus details at a closely-watched policy briefing. Property and tech subindices led losses.",
    originalUrl: "https://www.financialjuice.com/news/hsi-stimulus-miss" },
  { hAgo: 130, sourceLabel: "Reuters", category: "indices", tickers: ["VIX"],
    titleEn: "VIX collapses to multi-month low as macro calm persists",
    bodyEn: "The CBOE Volatility Index closed below 13 for the first time in three months as realized volatility continues to compress. Term structure remained in healthy contango with VIX futures showing little stress.",
    originalUrl: "https://www.reuters.com/markets/us/vix-multi-month-low" },

  // ===== crypto (8) =====
  { hAgo: 0.2, sourceLabel: "FinancialJuice", category: "crypto", tickers: ["BTC"],
    titleEn: "Bitcoin reclaims $68k as ETF inflows accelerate",
    bodyEn: "BTC pushed back above $68,000 after spot Bitcoin ETFs recorded their largest single-day net inflow in six weeks at $385 million. Open interest in CME BTC futures also jumped 4%, suggesting institutional re-engagement.",
    originalUrl: "https://www.financialjuice.com/news/btc-etf-inflows" },
  { hAgo: 1.2, sourceLabel: "CoinDesk", category: "crypto", tickers: ["ETH"],
    titleEn: "Ether climbs as ETH/BTC ratio bottoms",
    bodyEn: "Ether outperformed Bitcoin for a fourth consecutive session, with the ETH/BTC ratio bouncing off multi-year support. Traders cited renewed flows into spot ETH ETFs and a quiet calendar of unlock events.",
    originalUrl: "https://www.coindesk.com/markets/eth-outperforms-btc" },
  { hAgo: 4.5, sourceLabel: "FinancialJuice", category: "crypto", tickers: ["SOL"],
    titleEn: "Solana rallies 6% on memecoin volume revival",
    bodyEn: "SOL gained 6% in 24 hours as DEX volumes on Solana hit a 30-day high, driven by a fresh wave of memecoin launches. Network fees jumped to their highest level in two months.",
    originalUrl: "https://www.financialjuice.com/news/sol-memecoin-volume" },
  { hAgo: 12, sourceLabel: "The Block", category: "crypto", tickers: ["BTC"],
    titleEn: "Mt Gox transfers spook market briefly, dip bought",
    bodyEn: "An on-chain transfer of ~12,000 BTC from a wallet associated with Mt Gox creditors triggered a brief 1.5% Bitcoin selloff, but prices quickly recovered as bids stepped in around $66,800.",
    originalUrl: "https://www.theblock.co/post/mt-gox-transfer-dip-bought" },
  { hAgo: 26, sourceLabel: "CoinDesk", category: "crypto", tickers: ["ETH"],
    titleEn: "Ethereum staking ratio crosses 30% for the first time",
    bodyEn: "More than 30% of all circulating ETH is now staked, according to on-chain data. Analysts say the milestone reduces effective float and could amplify price moves in either direction.",
    originalUrl: "https://www.coindesk.com/tech/eth-staking-30-percent" },
  { hAgo: 44, sourceLabel: "FinancialJuice", category: "crypto", tickers: ["BTC"],
    titleEn: "MicroStrategy adds 5,200 BTC to treasury",
    bodyEn: "MicroStrategy disclosed the purchase of an additional 5,200 BTC at an average price of $66,400, taking its total holdings above 245,000 BTC. The buy was funded via a recent convertible note offering.",
    originalUrl: "https://www.financialjuice.com/news/mstr-treasury-5200-btc" },
  { hAgo: 90, sourceLabel: "The Block", category: "crypto", tickers: ["XRP"],
    titleEn: "XRP jumps on renewed ETF speculation",
    bodyEn: "XRP rallied 8% intraday as on-chain analysts spotted fresh institutional addresses accumulating, alongside renewed chatter about a possible spot XRP ETF filing. Volume on Asian exchanges led the move.",
    originalUrl: "https://www.theblock.co/post/xrp-etf-speculation" },
  { hAgo: 140, sourceLabel: "CoinDesk", category: "crypto", tickers: ["BTC", "ETH"],
    titleEn: "Crypto perp funding rates reset to neutral after long flush",
    bodyEn: "After a sharp 24-hour flush, perpetual swap funding rates on major BTC and ETH pairs reset close to zero, removing a key overhang for the next leg higher. Liquidation data showed ~$320m of forced unwinds.",
    originalUrl: "https://www.coindesk.com/markets/perp-funding-reset" },
];

const ITEMS: RawNewsItem[] = SEED.map((s, i) => ({
  id: `mock-${i + 1}`,
  publishedAt: ago(s.hAgo),
  sourceLabel: s.sourceLabel,
  category: s.category,
  tickers: s.tickers,
  titleEn: s.titleEn,
  bodyEn: s.bodyEn,
  originalUrl: s.originalUrl,
}));

export class MockNewsSource implements NewsSource {
  async fetch(opts: { category?: NewsCategory; limit?: number } = {}): Promise<RawNewsItem[]> {
    let arr = [...ITEMS].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
    if (opts.category) arr = arr.filter(x => x.category === opts.category);
    if (opts.limit) arr = arr.slice(0, opts.limit);
    return arr;
  }
}
