// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/firms-filter/RightDrawer.tsx": () => import("../components/mockups/firms-filter/RightDrawer.tsx"),
  "./components/mockups/firms-filter/TopBar.tsx": () => import("../components/mockups/firms-filter/TopBar.tsx")
};
