// AUTO-GENERATED by scripts/translate-firms.mjs — do not edit by hand.
// Chinese translations for firm long-text fields.

export interface FirmZh {
  aiSummaryZh: string;
  offerDescriptionZh: string;
  consistencyRulesZh: { program: string; rule: string }[];
  leverageZh: string[];
}

export const FIRMS_ZH: Record<string, FirmZh> = {
  "alpha-futures": {
    "aiSummaryZh": "Alpha Futures 成立于 2024 年 7 月，总部位于英国。公司提供期货交易一阶段项目，支持 TradingView、Quantower、Tradovate、NinjaTrader 和 Deepcharts 平台。作为 Alpha Capital Group 进军期货领域的产品，其核心目标是为美国交易者提供更稳定的交易环境，同时丰富公司业务线。平台主打宽松出金政策，并承诺提供交易者活动和教育支持。",
    "offerDescriptionZh": "挑战赛账户立减 15%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "Premium 等级最大合约数（按账户规模）",
      "$50,000 账户：最多 4 份合约（40 微型合约）",
      "$100,000 账户：最多 8 份合约（80 微型合约）",
      "$150,000 账户：最多 12 份合约（120 微型合约）",
      "Advanced 等级最大合约数（按账户规模）",
      "$50,000 账户：最多 5 份合约（50 微型合约）",
      "$100,000 账户：最多 10 份合约（100 微型合约）",
      "$150,000 账户：最多 15 份合约（150 微型合约）",
      "Zero 等级最大合约数（按账户规模）",
      "$25,000 账户：最多 1 份合约（10 微型合约）",
      "$50,000 账户：最多 3 份合约（30 微型合约）",
      "$100,000 账户：最多 6 份合约（60 微型合约）"
    ]
  },
  "apex-trader-funding": {
    "aiSummaryZh": "Apex Trader Funding 成立于 2021 年 1 月，总部位于美国，专注期货交易，提供一阶段评估计划。账户规模从 $25,000 至 $300,000 可选。支持 Bookmap、Sierra Chart、MotiveWave、TradingView、EdgeProX、Finamark、Jigsaw Daytradr、Quantower、R Trader Pro、VolFix、Rithmic、Tradovate、WealthCharts、NinjaTrader 和 ATAS Orderflow Trading 等多个交易平台。交易品种涵盖小标普 500、纳斯达克 100、小道琼斯等股指期货及利率产品。",
    "offerDescriptionZh": "立减 90% 折扣 + 重置账户优惠",
    "consistencyRulesZh": [],
    "leverageZh": [
      "各账户规模允许的最大合约手数",
      "评估阶段",
      "$25,000 账户：最多 4 手迷你/40 手微型",
      "$50,000 账户：最多 6 手迷你/60 手微型",
      "$100,000 账户：最多 8 手迷你/80 手微型",
      "$150,000 账户：最多 12 手迷你/120 手微型",
      "模拟签约账户（实盘表现账户）",
      "$25,000 账户：最多 2 手迷你/20 手微型",
      "$50,000 账户：最多 4 手迷你/40 手微型",
      "$100,000 账户：最多 6 手迷你/60 手微型",
      "$150,000 账户：最多 10 手迷你/100 手微型"
    ]
  },
  "aquafutures": {
    "aiSummaryZh": "AquaFutures成立于2024年11月，是一家总部位于阿联酋的自营公司。专注期货交易，提供一阶段挑战赛项目。支持Volumetrica Trading和Deepcharts两大交易平台。基于79份评价，平台综合评分3.8/5分。致力于为交易者提供纯期货交易机会。",
    "offerDescriptionZh": "所有挑战赛账户立减60%",
    "consistencyRulesZh": [
      {
        "program": "Standard",
        "rule": "单个交易日盈利不得超过周期总盈利的40%（签约后）"
      },
      {
        "program": "Beginner",
        "rule": "单个交易日盈利不得超过周期总盈利的40%（评估和签约后）"
      },
      {
        "program": "Instant",
        "rule": "最大盈利日不得超过周期总盈利的20%（签约后）"
      },
      {
        "program": "Instant Pro",
        "rule": "最大盈利日不得超过周期总盈利的15%（签约后）"
      }
    ],
    "leverageZh": [
      "初级档",
      "$25K：1手",
      "$50K：3手",
      "$100K：6手",
      "$150K：9手",
      "标准档",
      "$25K：2手",
      "$50K：5手",
      "$100K：10手",
      "$150K：15手",
      "即时入金",
      "$25K：1手"
    ]
  },
  "blue-guardian-futures": {
    "aiSummaryZh": "Blue Guardian Futures 总部位于阿联酋，成立于 2024 年 11 月，专注期货交易。平台支持一阶段和即时入金两种计划，交易可通过 Tradovate、NinjaTrader 和 Deepcharts 进行。用户评分 4.4/5（84 条评价），作为年底新晋公司，在期货领域具有竞争力。",
    "offerDescriptionZh": "全部挑战赛账户立减 35% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Standard",
        "rule": "单日利润不得超过总利润的 40%，评估与签约阶段均适用"
      },
      {
        "program": "Pro",
        "rule": "单日利润不得超过总利润的 35%，签约阶段适用"
      },
      {
        "program": "Rapid",
        "rule": "单日利润不得超过总利润的 40%，评估与签约阶段均适用"
      },
      {
        "program": "Instant",
        "rule": "单日利润不得超过总利润的 20%"
      }
    ],
    "leverageZh": [
      "Standard",
      "$50K - 3 迷你（30 微型）",
      "$100K - 6 迷你（60 微型）",
      "$150K - 9 迷你（90 微型）",
      "Guardian",
      "$50K - 5 迷你（50 微型）",
      "$100K - 10 迷你（100 微型）",
      "$150K - 15 迷你（150 微型）",
      "Instant",
      "$50K - 5 迷你（50 微型）",
      "$100K - 10 迷你（100 微型）",
      "$150K - 15 迷你（150 微型）"
    ]
  },
  "blueberry-futures": {
    "aiSummaryZh": "Blueberry Futures 提供灵活的期货交易账户，支持多档位资金配置，杠杆倍数与账户规模相匹配，满足不同风险偏好的交易者需求。",
    "offerDescriptionZh": "启动优惠，享 60% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "$25,000 账户：最高 1 份合约（10 微型合约）",
      "$50,000 账户：最高 2 份合约（20 微型合约）",
      "$100,000 账户：最高 6 份合约（60 微型合约）",
      "$150,000 账户：最高 9 份合约（90 微型合约）"
    ]
  },
  "e8-futures": {
    "aiSummaryZh": "E8 Futures 成立于 2024 年 12 月，总部位于美国，提供一阶段挑战赛项目，支持 TradingView 和 Tradovate 交易平台。平台基于 18 条评价获得 4.7 分的高评分，展现出良好的用户口碑。",
    "offerDescriptionZh": "所有挑战赛账户享 20% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": []
  },
  "earn2trade": {
    "aiSummaryZh": "Earn2Trade 成立于 2016 年 9 月，总部位于美国。提供期货交易工具，采用一阶段入金模式。账户规模从 $25,000 到 $200,000 不等。支持 Bookmap、Investor/RT、Sierra Chart、MotiveWave、TradingView、Finamark、OverCharts、Trade Navigator、Jigsaw Daytradr、MultiCharts、Quantower、R Trader Pro、VolFix、Rithmic、Tradovate 等多个交易平台。",
    "offerDescriptionZh": "所有挑战赛账户享 60% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "各账户规模允许的最大合约数",
      "高手之路迷你版允许的最大合约数",
      "$50k：最多 6 份合约",
      "$100k：最多 12 份合约",
      "$150k：最多 15 份合约",
      "$200k：最多 16 份合约",
      "交易生涯之路允许的最大合约数：",
      "$100k：最多 12 份合约",
      "$50k：最多 6 份合约",
      "$25k：最多 3 份合约"
    ]
  },
  "funded-futures-family": {
    "aiSummaryZh": "Funded Futures Family 成立于 2024 年 10 月，总部位于美国。公司提供期货交易，支持即时入金和一阶段两种评估方式。交易平台包括 TradingView、Tradovate、WealthCharts 和 NinjaTrader。客户评分 4.6/5（基于 12 条评价）。",
    "offerDescriptionZh": "立减 75% 首发优惠",
    "consistencyRulesZh": [],
    "leverageZh": [
      "Prime、Premier Plus（日盘及盘中）及 Velocity Max 合约规模限制",
      "$25,000 账户：最多 3 手迷你合约或 30 手微型合约",
      "$50,000 账户：最多 5 手迷你合约或 50 手微型合约",
      "$100,000 账户：最多 10 手迷你合约或 100 手微型合约",
      "$150,000 账户：最多 15 手迷你合约或 150 手微型合约",
      "S2F Max 合约规模限制",
      "$25,000 账户：最多 1 手迷你合约或 10 手微型合约",
      "$50,000 账户：最多 5 手迷你合约或 50 手微型合约",
      "$100,000 账户：最多 10 手迷你合约或 100 手微型合约",
      "$150,000 账户：最多 15 手迷你合约或 150 手微型合约"
    ]
  },
  "fundednext-futures": {
    "aiSummaryZh": "FundedNext Futures 是一家成立于 2025 年 4 月的阿联酋自营公司，专注期货交易。提供一阶段挑战赛计划，支持 TradingView、Tradovate 和 NinjaTrader 平台。可交易期货合约，用户评分 4.3/5（57 条评价）。",
    "offerDescriptionZh": "全部挑战赛账户享 47% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "传统评估",
      "$25K - 2 份迷你合约，20 份微型合约",
      "$50K - 3 份迷你合约，30 份微型合约",
      "$100K - 5 份迷你合约，50 份微型合约",
      "$25K - 最多 3 份迷你合约，30 份微型合约",
      "$50K - 最多 5 份迷你合约，50 份微型合约",
      "$100K - 最多 7 份迷你合约，70 份微型合约",
      "快速评估",
      "$25K - 2 份迷你合约，10 份微型合约",
      "$50K - 3 份迷你合约，15 份微型合约",
      "$100K - 5 份迷你合约，25 份微型合约",
      "$25K - 最多 3 份迷你合约，15 份微型合约"
    ]
  },
  "futureselite": {
    "aiSummaryZh": "FuturesElite提供多档位自营账户，覆盖评估、签约及即时入金三大类计划。支持期货合约交易，配套灵活的杠杆方案与一致性规则，适合不同风险偏好的交易者。",
    "offerDescriptionZh": "挑战赛账户全部享受40% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Custom Evaluation",
        "rule": "单个交易日利润不得超过总利润的50%（评估账户适用）"
      },
      {
        "program": "Prime",
        "rule": "单个交易日利润不得达到或超过总利润的40%（签约账户适用）"
      },
      {
        "program": "Elite Sim Funded",
        "rule": "单个交易日利润不得超过总利润的50%（评估账户适用）"
      },
      {
        "program": "Instant",
        "rule": "第1、2次出金：一致性评分20% | 第3次出金：一致性评分25% | 第4次出金：一致性评分30%"
      },
      {
        "program": "Custom Instant",
        "rule": "第1次出金：一致性评分20% | 第2次出金：一致性评分25% | 第3次出金：一致性评分30%"
      },
      {
        "program": "Custom Instant and Instant 25k (Fixed at 20%)",
        "rule": "单个交易日利润不得等于或超过总利润的20%"
      }
    ],
    "leverageZh": [
      "Prime计划及Custom Evaluation",
      "$50K账户：3份合约 | 最多3份迷你合约或30份微型合约",
      "$100K账户：8份合约 | 最多8份迷你合约或80份微型合约",
      "$150K账户：12份合约 | 最多12份迷你合约或120份微型合约",
      "Elite计划",
      "$50K账户：4份合约 | 最多4份迷你合约或40份微型合约",
      "$100K账户：8份合约 | 最多8份迷你合约或80份微型合约",
      "$150K账户：12份合约 | 最多12份迷你合约或120份微型合约",
      "Instant计划及Instant Custom",
      "$25K账户：2份合约 | 最多2份迷你合约或20份微型合约",
      "$50K账户：4份合约 | 最多4份迷你合约或40份微型合约",
      "$100K账户：8份合约 | 最多8份迷你合约或80份微型合约"
    ]
  },
  "goat-funded-futures": {
    "aiSummaryZh": "Goat Funded Futures 成立于 2024 年 11 月，总部位于香港。公司提供期货交易，支持一阶段和即时入金两种项目类型，兼容 TradingView、Quantower、Tradovate、Volumetrica Trading、NinjaTrader、ATAS Orderflow Trading、Deepmap 和 Deepcharts 等主流交易平台。评分 4.3/5（11 条评价）。",
    "offerDescriptionZh": "50% 折扣 + 特别优惠",
    "consistencyRulesZh": [
      {
        "program": "EOD Accounts",
        "rule": "单日盈利不得超过评估阶段总利润的 50%，签约后不得超过 30%"
      },
      {
        "program": "Instant",
        "rule": "单日盈利不得超过总利润的 20%（即时入金，无评估阶段）"
      },
      {
        "program": "Sprint",
        "rule": "签约后单日盈利不得超过总利润的 30%，评估阶段无此限制。评估阶段需达 50% 一致性评分，模拟签约无要求"
      }
    ],
    "leverageZh": [
      "EOD",
      "$50K：5 迷你合约 / 50 微型合约",
      "$100K：9 迷你合约 / 90 微型合约",
      "$150K：12 迷你合约 / 120 微型合约",
      "Sprint",
      "$25K：3 迷你合约 / 30 微型合约",
      "$50K：5 迷你合约 / 50 微型合约",
      "$100K：7 迷你合约 / 70 微型合约",
      "Instant",
      "$25K：3 迷你合约 / 30 微型合约",
      "$50K：4 迷你合约 / 40 微型合约",
      "$75K：5 迷你合约 / 50 微型合约"
    ]
  },
  "hola-prime-futures": {
    "aiSummaryZh": "Hola Prime Futures 是一家 2025 年 6 月成立的香港自营公司，专注期货交易。提供即时入金和一阶段两种交易计划，支持 Tradovate、Dx Futures 和 NinjaTrader 平台。公司获得 5/5 满分评价，为交易者提供多平台期货交易服务。",
    "offerDescriptionZh": "50% 折扣优惠活动",
    "consistencyRulesZh": [],
    "leverageZh": [
      "最大敞口限制",
      "一阶段 Prime 挑战赛",
      "$25,000 账户：最多 1 手迷你合约或 10 手微型合约",
      "$50,000 账户：最多 3 手迷你合约或 30 手微型合约",
      "$100,000 账户：最多 7 手迷你合约或 70 手微型合约",
      "$150,000 账户：最多 10 手迷你合约或 100 手微型合约",
      "直接账户",
      "$25,000 账户：最多 1 手迷你合约或 10 手微型合约",
      "$50,000 账户：最多 3 手迷你合约或 30 手微型合约",
      "$100,000 账户：最多 6 手迷你合约或 60 手微型合约",
      "$150,000 账户：最多 9 手迷你合约或 90 手微型合约"
    ]
  },
  "lucid-trading": {
    "aiSummaryZh": "Lucid Trading 成立于 2025 年 3 月，总部位于美国，专注期货交易。平台支持 Bookmap、Sierra Chart、MotiveWave、Jigsaw Daytradr、MultiCharts、Quantower、R Trader Pro、Tradovate、NinjaTrader、ATAS Orderflow Trading 及 Tradesea Tradingview。提供即时入金和一阶段两种签约模式，客户评分 4.6/5（39 条评价）。",
    "offerDescriptionZh": "Flex & Pro 账户享 40% 折扣（限 5 次使用）",
    "consistencyRulesZh": [
      {
        "program": "LucidPro",
        "rule": "签约后需保持 40% 一致性"
      },
      {
        "program": "LucidFlex",
        "rule": "评估阶段需保持 50% 一致性"
      },
      {
        "program": "LucidDirect",
        "rule": "签约后需保持 20% 一致性"
      }
    ],
    "leverageZh": [
      "最大合约规模",
      "$25K - 2 份迷你合约或 20 份微型合约",
      "$50K - 4 份迷你合约或 40 份微型合约",
      "$100K - 6 份迷你合约或 60 份微型合约",
      "$150K - 10 份迷你合约或 100 份微型合约"
    ]
  },
  "my-funded-futures": {
    "aiSummaryZh": "My Funded Futures 成立于 2023 年 11 月，总部位于美国。公司提供一阶段期货交易计划，账户规模从 $50K 至 $150K 不等。支持 TradingView、Quantower、Volbook、Volsys、Tradovate、Volumetrica Trading、NinjaTrader 及 ATAS Orderflow Trading 等平台。可交易 CME、CBOT、COMEX 和 NYMEX 等交易所的期货合约，并按资产类别提供差异化杠杆：外汇 1:100、指数 1:20、贵金属（黄金 1:80 等）。",
    "offerDescriptionZh": "全部挑战赛账户享 50% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Rapid",
        "rule": "交易者单日盈利不得超过挑战赛阶段总盈利的 50%。签约阶段无一致性要求。"
      },
      {
        "program": "Pro",
        "rule": "交易者单日盈利不得超过挑战赛阶段总盈利的 50%。签约阶段无一致性要求。（$50K 追加账户的挑战赛和签约阶段均无一致性要求）"
      },
      {
        "program": "Flex",
        "rule": "交易者单日盈利不得超过挑战赛阶段总盈利的 50%。签约阶段无一致性要求。"
      },
      {
        "program": "Builder",
        "rule": "交易者单日盈利不得超过签约阶段总盈利的 50%。挑战赛阶段无一致性要求。"
      }
    ],
    "leverageZh": [
      "各账户规模最大合约持仓",
      "Flex",
      "$25K 账户：最多 3 份迷你合约或 30 份微型合约",
      "$50K 账户：最多 5 份迷你合约或 50 份微型合约",
      "Pro",
      "$50K 账户：最多 3 份迷你合约或 30 份微型合约",
      "$100K 账户：最多 6 份迷你合约或 60 份微型合约",
      "$150K 账户：最多 9 份迷你合约或 90 份微型合约",
      "Rapid",
      "$25K 账户：最多 3 份迷你合约或 30 份微型合约",
      "$50K 账户：最多 5 份迷你合约或 50 份微型合约",
      "$100K 账户：最多 10 份迷你合约或 100 份微型合约"
    ]
  },
  "take-profit-trader": {
    "aiSummaryZh": "Take Profit Trader 是一家自营交易平台，为交易者提供挑战赛账户和签约账户机制。平台支持多档位账户（$25K 至 $150K），根据账户规模提供灵活的杠杆配置，帮助交易者通过评估后获得资金支持。",
    "offerDescriptionZh": "所有挑战赛账户享受 50% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "杠杆：按账户规模配置的最大合约数",
      "$25K：3 份合约 / 30 微型合约",
      "$50K：6 份合约 / 60 微型合约",
      "$75K：9 份合约 / 90 微型合约",
      "$100K：12 份合约 / 120 微型合约",
      "$150K：15 份合约 / 150 微型合约"
    ]
  },
  "the-trading-pit-futures": {
    "aiSummaryZh": "The Trading Pit Futures 成立于 2022 年 10 月，注册地列支敦士登。提供期货、外汇、指数、商品、加密货币及股票交易，支持一阶段和两阶段挑战赛。账户规模从 $10,000 至 $100,000 不等。兼容 TradingView、Quantower、R Trader Pro、Volsys、Tradovate、R Trader、NinjaTrader、ATAS Orderflow Trading、MetaTrader 4、MetaTrader 5 及 Bookmap 等平台。",
    "offerDescriptionZh": "所有挑战赛账户享 30% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "杠杆：各账户档位最大合约数限额",
      "The Trading Pit - Futures Prime",
      "$50K 账户：5 手合约 / 50 微型合约",
      "$100K 账户：10 手合约 / 100 微型合约",
      "$150K 账户：15 手合约 / 150 微型合约"
    ]
  },
  "top-one-futures": {
    "aiSummaryZh": "Top One Futures 成立于 2025 年 4 月，总部位于美国，专注期货交易。公司提供一阶段签约计划，支持 TradingView、Tradovate 和 NinjaTrader 平台。基于 72 条用户评价，平台获得 4.7/5.0 的评分。以期货交易为核心，单阶段快速入金模式，多平台集成。",
    "offerDescriptionZh": "所有挑战赛账户立减 60%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "$25,000 账户 – 最多 1 份迷你合约（或 10 份微型合约）",
      "$50,000 账户 – 最多 3 份迷你合约（或 30 份微型合约）",
      "$100,000 账户 – 最多 5 份迷你合约（或 50 份微型合约）",
      "$150,000 账户 – 最多 7 份迷你合约（或 70 份微型合约）"
    ]
  },
  "topstep": {
    "aiSummaryZh": "Topstep 是一家成立于 2012 年 1 月的美国自营公司，提供期货交易一阶段计划。账户规模从 $50,000 到 $150,000 不等。支持 TopstepX、NinjaTrader、Quantower、T4、R Trader Pro、Atas Orderflow Trading、MotiveWave、VolFix、Bookmap、Investor/RT、Jigsaw、Daytradr、MultiCharts、Sierra Chart 和 Trade Navigator 等交易平台，可交易 CME 股指期货及微型合约等产品。",
    "offerDescriptionZh": "",
    "consistencyRulesZh": [
      {
        "program": "Combine",
        "rule": "单日利润不得超过总利润的 50%。（挑战赛）"
      },
      {
        "program": "Express Funded Standard Path",
        "rule": "无一致性要求。（签约账户）"
      },
      {
        "program": "Express Funded Consistency Path",
        "rule": "单日利润不得超过总利润的 40%。（签约账户）"
      }
    ],
    "leverageZh": [
      "杠杆 = 根据账户规模允许的最大合约数"
    ]
  },
  "tradeday": {
    "aiSummaryZh": "TradeDay 是一家成立于 2020 年 1 月的美国自营公司，专注期货交易，提供一阶段挑战赛。账户规模从 $10,000 到 $250,000，支持 TradingView、Jigsaw Daytradr、Tradovate、TradeDayX 和 NinjaTrader 平台，交易品种覆盖 CME、CBOT、NYMEX 和 COMEX 主流期货合约。公司评分 4.8/5（11 条评价）。",
    "offerDescriptionZh": "所有挑战赛账户立减 30%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "各账户档位允许的最大合约持仓规模",
      "$50,000 账户：最多 5 手迷你合约或 50 手微型合约",
      "$100,000 账户：最多 10 手迷你合约或 100 手微型合约",
      "$150,000 账户：最多 15 手迷你合约或 150 手微型合约"
    ]
  },
  "tradeify": {
    "aiSummaryZh": "Tradeify 成立于 2024 年 6 月，总部位于美国。公司专注期货交易，提供一阶段和即时入金两种签约计划。支持 Sierra Chart、TradingView、Quantower、Rithmic、Tradovate、WealthCharts、NinjaTrader 和 Tradesea Tradingview 等交易平台。基于 155 条评价，Tradeify 获得 4.7 分（满分 5 分）的用户评价。",
    "offerDescriptionZh": "所有挑战赛账户立减 40%",
    "consistencyRulesZh": [
      {
        "program": "Consistency Rule of 35%",
        "rule": "适用于所有 Growth Sim 签约账户，单日最大收益不超过总利润的 35%。"
      },
      {
        "program": "Consistency Rule of 20%",
        "rule": "适用于所有 Lightning 签约账户，单日最大收益第一次出金不超过 20%，第二次不超过 25%，第三次及以后不超过 30%。"
      },
      {
        "program": "Consistency Rule of 40%",
        "rule": "适用于所有 Select 账户，评估阶段单日最大收益不超过 40%。"
      }
    ],
    "leverageZh": [
      "Growth、Select 和 Lightning 签约账户杠杆规则：",
      "$25K 账户：最高 1 手合约（10 微型合约）",
      "$50K 账户：最高 4 手合约（40 微型合约）",
      "$100K 账户：最高 8 手合约（80 微型合约）",
      "$150K 账户：最高 12 手合约（120 微型合约）"
    ]
  },
  "traders-launch": {
    "aiSummaryZh": "Traders Launch 成立于 2023 年 8 月，是一家美国自营公司，提供期货交易及一阶段挑战赛。账户规模从 $5,000 到 $100,000 不等，支持 Quantower、Volumetrica Trading、IBKR 和 NinjaTrader 平台。可交易约 300 只流动性良好的股票、ETF 及指数产品（如 SPX、NDX、US30、GLD），评分 4.6/5（基于 19 条评价）。",
    "offerDescriptionZh": "所有挑战赛账户立减 15% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "杠杆：各账户最大合约头寸",
      "纽约时段",
      "$100K - 5 手微型",
      "$200K - 1 手小型或 10 手微型",
      "$300K - 2 手小型或 20 手微型",
      "完整时段",
      "$100K - 2 手小型或 20 手微型",
      "$200K - 4 手小型或 40 手微型",
      "$300K - 6 手小型或 60 手微型"
    ]
  }
};

export function findFirmZh(slug: string): FirmZh | undefined {
  return FIRMS_ZH[slug];
}
