// AUTO-GENERATED by scripts/translate-firms.mjs — do not edit by hand.
// Chinese translations for firm long-text fields.

export interface FirmZh {
  aiSummaryZh: string;
  offerDescriptionZh: string;
  consistencyRulesZh: { program: string; rule: string }[];
  leverageZh: string[];
}

export const FIRMS_ZH: Record<string, FirmZh> = {
  "alpha-futures": {
    "aiSummaryZh": "Alpha Futures 成立于 2024 年 7 月，总部位于英国。公司提供期货交易一阶段挑战赛，支持 TradingView、Quantower、Tradovate、NinjaTrader 和 Deepcharts 等平台。作为 Alpha Capital Group 进军期货领域的重要举措，Alpha Futures 致力于为美国交易者提供更稳定的交易环境，同时丰富公司产品线。平台强调出金政策灵活友好，并承诺提供交易者活动与教育资源。",
    "offerDescriptionZh": "挑战赛账户立减 15%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "Premium 账户 - 单账户最大合约数限额",
      "$50,000 账户：最多 4 手合约（40 微型合约）",
      "$100,000 账户：最多 8 手合约（80 微型合约）",
      "$150,000 账户：最多 12 手合约（120 微型合约）",
      "Advanced 账户 - 单账户最大合约数限额",
      "$50,000 账户：最多 5 手合约（50 微型合约）",
      "$100,000 账户：最多 10 手合约（100 微型合约）",
      "$150,000 账户：最多 15 手合约（150 微型合约）",
      "Zero 账户 - 单账户最大合约数限额",
      "$25,000 账户：最多 1 手合约（10 微型合约）",
      "$50,000 账户：最多 3 手合约（30 微型合约）",
      "$100,000 账户：最多 6 手合约（60 微型合约）"
    ]
  },
  "apex-trader-funding": {
    "aiSummaryZh": "Apex Trader Funding 成立于 2021 年 1 月，总部位于美国，专注期货交易，提供一阶段签约计划。账户规模从 $25,000 至 $300,000 可选。支持 Bookmap、Sierra Chart、MotiveWave、TradingView、EdgeProX、Finamark、Jigsaw Daytradr、Quantower、R Trader Pro、VolFix、Rithmic、Tradovate、WealthCharts、NinjaTrader 及 ATAS Orderflow Trading 等多个交易平台。可交易品种包括 E-mini S&P 500、NASDAQ 100、Mini-DOW 等股指期货及其他衍生品。",
    "offerDescriptionZh": "享受 90% 折扣 + 重置折优惠",
    "consistencyRulesZh": [
      {
        "program": "Standard",
        "rule": "单日盈利不得超过总盈利的 40%（签约账户）"
      },
      {
        "program": "Beginner",
        "rule": "单日盈利不得超过总盈利的 40%（签约及评估账户）"
      },
      {
        "program": "Instant",
        "rule": "单个盈利交易日不得超过周期总盈利的 20%（签约账户）"
      },
      {
        "program": "Instant Pro",
        "rule": "单个盈利交易日不得超过周期总盈利的 15%（签约账户）"
      }
    ],
    "leverageZh": [
      "各账户规模最大合约持仓量",
      "评估阶段",
      "$25,000 账户：最高 4 个迷你合约 / 40 个微型合约",
      "$50,000 账户：最高 6 个迷你合约 / 60 个微型合约",
      "$100,000 账户：最高 8 个迷你合约 / 80 个微型合约",
      "$150,000 账户：最高 12 个迷你合约 / 120 个微型合约",
      "模拟签约账户（业绩账户）",
      "$25,000 账户：最高 2 个迷你合约 / 20 个微型合约",
      "$50,000 账户：最高 4 个迷你合约 / 40 个微型合约",
      "$100,000 账户：最高 6 个迷你合约 / 60 个微型合约",
      "$150,000 账户：最高 10 个迷你合约 / 100 个微型合约"
    ]
  },
  "aquafutures": {
    "aiSummaryZh": "AquaFutures 成立于 2024 年 11 月，是一家总部位于阿拉伯联合酋长国的自营公司。公司专注期货交易，提供一阶段（1 Step）挑战赛计划。支持 Volumetrica Trading 和 Deepcharts 两大交易平台。基于 79 条评价，平台评分达 3.8/5。",
    "offerDescriptionZh": "所有挑战赛账户立减 60%",
    "consistencyRulesZh": [
      {
        "program": "Standard",
        "rule": "单个交易日利润不得超过周期总利润的 40%（签约账户）"
      },
      {
        "program": "Beginner",
        "rule": "单个交易日利润不得超过周期总利润的 40%（签约及评估阶段）"
      },
      {
        "program": "Instant",
        "rule": "单个交易日最大利润不得超过周期总利润的 20%（签约账户）"
      },
      {
        "program": "Instant Pro",
        "rule": "单个交易日最大利润不得超过周期总利润的 15%（签约账户）"
      }
    ],
    "leverageZh": [
      "初级（Beginner）",
      "$25K：1 份合约",
      "$50K：3 份合约",
      "$100K：6 份合约",
      "$150K：9 份合约",
      "标准（Standard）",
      "$25K：2 份合约",
      "$50K：5 份合约",
      "$100K：10 份合约",
      "$150K：15 份合约",
      "即时入金（Instant）",
      "$25K：1 份合约"
    ]
  },
  "blue-guardian-futures": {
    "aiSummaryZh": "Blue Guardian Futures 成立于 2024 年 11 月，总部位于阿联酋，专注期货交易。公司提供一阶段与即时入金两种交易模式，支持 Tradovate、NinjaTrader 和 Deepcharts 平台。用户评分 4.4/5（基于 84 条评价），作为新兴期货自营公司，已获得市场认可。",
    "offerDescriptionZh": "全部挑战赛账户立减 35% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Standard",
        "rule": "单日利润贡献不得超过总利润的 40%，评估期和签约期均适用"
      },
      {
        "program": "Pro",
        "rule": "单日利润贡献不得超过总利润的 35%，仅在签约期适用"
      },
      {
        "program": "Rapid",
        "rule": "单日利润贡献不得超过总利润的 40%，评估期和签约期均适用"
      },
      {
        "program": "Instant",
        "rule": "单日利润贡献不得超过总利润的 20%"
      }
    ],
    "leverageZh": [
      "Standard",
      "$50K - 3 迷你（30 微型）",
      "$100K - 6 迷你（60 微型）",
      "$150K - 9 迷你（90 微型）",
      "Guardian",
      "$50K - 5 迷你（50 微型）",
      "$100K - 10 迷你（100 微型）",
      "$150K - 15 迷你（150 微型）",
      "Instant",
      "$50K - 5 迷你（50 微型）",
      "$100K - 10 迷你（100 微型）",
      "$150K - 15 迷你（150 微型）"
    ]
  },
  "blueberry-futures": {
    "aiSummaryZh": "Blueberry Futures 是一家专业期货自营公司，提供多档位账户和灵活的杠杆配置。通过结构化的挑战赛和评估流程，帮助交易者快速获得签约资金，实现稳定的交易收益。",
    "offerDescriptionZh": "推出优惠：立减 60%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "$25,000 账户：最高 1 手合约（10 微型合约）",
      "$50,000 账户：最高 2 手合约（20 微型合约）",
      "$100,000 账户：最高 6 手合约（60 微型合约）",
      "$150,000 账户：最高 9 手合约（90 微型合约）"
    ]
  },
  "e8-futures": {
    "aiSummaryZh": "E8 Futures 成立于 2024 年 12 月，总部位于美国。公司提供一阶段挑战赛项目，支持 TradingView 和 Tradovate 交易平台。基于 18 条用户评价，平台获得 4.7/5 的高分认可。",
    "offerDescriptionZh": "所有挑战赛账户享 20% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": []
  },
  "earn2trade": {
    "aiSummaryZh": "Earn2Trade 成立于 2016 年 9 月，总部位于美国。提供期货交易工具，采用一阶段入金模式。账户规模从 $25,000 至 $200,000 不等。支持 Bookmap、Investor/RT、Sierra Chart、MotiveWave、TradingView、Finamark、OverCharts、Trade Navigator、Jigsaw Daytradr、MultiCharts、Quantower、R Trader Pro、VolFix、Rithmic、Tradovate、Inside Edge Trader、Photon、QScalp、QSI-Quick Screen Trading、R Trader、Scalp Tool、NinjaTrader 和 ATAS 等多个交易平台。",
    "offerDescriptionZh": "所有挑战赛账户立减 60%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "各账户规模允许的最大合约数",
      "The Gauntlet Mini 允许的最大合约数",
      "$50K：最多 6 手",
      "$100K：最多 12 手",
      "$150K：最多 15 手",
      "$200K：最多 16 手",
      "Trader Career Path 允许的最大合约数",
      "$100K：最多 12 手",
      "$50K：最多 6 手",
      "$25K：最多 3 手"
    ]
  },
  "funded-futures-family": {
    "aiSummaryZh": "Funded Futures Family 成立于 2024 年 10 月，总部位于美国。公司提供两种期货交易项目：即时入金和一阶段。支持 TradingView、Tradovate、WealthCharts 和 NinjaTrader 等交易平台。基于 12 条评价，公司综合评分达 4.6 分（满分 5 分）。",
    "offerDescriptionZh": "享受 75% 折扣的上线优惠",
    "consistencyRulesZh": [],
    "leverageZh": [
      "Prime、Premier Plus（日终和日内）及 Velocity Max 项目的合约规模限制",
      "$25,000 账户：最多 3 张迷你合约或 30 张微型合约",
      "$50,000 账户：最多 5 张迷你合约或 50 张微型合约",
      "$100,000 账户：最多 10 张迷你合约或 100 张微型合约",
      "$150,000 账户：最多 15 张迷你合约或 150 张微型合约",
      "S2F Max 项目的合约规模限制",
      "$25,000 账户：最多 1 张迷你合约或 10 张微型合约",
      "$50,000 账户：最多 5 张迷你合约或 50 张微型合约",
      "$100,000 账户：最多 10 张迷你合约或 100 张微型合约",
      "$150,000 账户：最多 15 张迷你合约或 150 张微型合约"
    ]
  },
  "fundednext-futures": {
    "aiSummaryZh": "FundedNext Futures 成立于 2025 年 4 月，总部位于阿联酋。公司专注期货交易，提供一阶段即时入金计划。支持 TradingView、Tradovate 和 NinjaTrader 等多个平台，交易品种为期货合约。基于 57 条评价，综合评分 4.3/5。",
    "offerDescriptionZh": "所有挑战赛账户享 47% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Custom Evaluation",
        "rule": "单日利润不得超过总利润的 50%（仅评估账户）"
      },
      {
        "program": "Prime",
        "rule": "单日利润不得等于或超过总利润的 40%（签约账户）"
      },
      {
        "program": "Elite Sim Funded",
        "rule": "单日利润不得超过总利润的 50%（仅评估账户）"
      },
      {
        "program": "Instant",
        "rule": "第 1、2 次出金：一致性评分 20% | 第 3 次出金：25% | 第 4 次出金：30%"
      },
      {
        "program": "Custom Instant",
        "rule": "第 1 次出金：一致性评分 20% | 第 2 次出金：25% | 第 3 次出金：30%"
      },
      {
        "program": "Custom Instant and Instant 25k (Fixed at 20%)",
        "rule": "单日利润不得等于或超过总利润的 20%"
      }
    ],
    "leverageZh": [
      "Legacy Evaluation",
      "$25K - 2 手迷你合约，20 手微型合约",
      "$50K - 3 手迷你合约，30 手微型合约",
      "$100K - 5 手迷你合约，50 手微型合约",
      "$25K - 最多 3 手迷你合约，30 手微型合约",
      "$50K - 最多 5 手迷你合约，50 手微型合约",
      "$100K - 最多 7 手迷你合约，70 手微型合约",
      "Rapid Evaluation",
      "$25K - 2 手迷你合约，10 手微型合约",
      "$50K - 3 手迷你合约，15 手微型合约",
      "$100K - 5 手迷你合约，25 手微型合约",
      "$25K - 最多 3 手迷你合约，15 手微型合约"
    ]
  },
  "futureselite": {
    "aiSummaryZh": "FuturesElite 是一家提供多层级期货交易评估与签约账户的自营公司。平台支持灵活的杠杆配置、多种分润模式和即时入金选项，满足不同交易风格的专业交易者需求。",
    "offerDescriptionZh": "所有挑战赛账户享受 40% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Custom Evaluation",
        "rule": "单日盈利不超过总盈利的 50%（仅评估账户适用）"
      },
      {
        "program": "Prime",
        "rule": "单日盈利不得达到或超过总盈利的 40%（仅签约账户适用）"
      },
      {
        "program": "Elite Sim Funded",
        "rule": "单日盈利不超过总盈利的 50%（仅评估账户适用）"
      },
      {
        "program": "Instant",
        "rule": "第 1、2 次出金：一致性评分 20% | 第 3 次出金：一致性评分 25% | 第 4 次出金：一致性评分 30%"
      },
      {
        "program": "Custom Instant",
        "rule": "第 1 次出金：一致性评分 20% | 第 2 次出金：一致性评分 25% | 第 3 次出金：一致性评分 30%"
      },
      {
        "program": "Custom Instant and Instant 25k (Fixed at 20%)",
        "rule": "单日盈利不得等于或超过总盈利的 20%"
      }
    ],
    "leverageZh": [
      "Prime 计划与 Custom 评估",
      "$50K 账户：3 张合约 | 最多 3 张迷你合约或 30 张微型合约",
      "$100K 账户：8 张合约 | 最多 8 张迷你合约或 80 张微型合约",
      "$150K 账户：12 张合约 | 最多 12 张迷你合约或 120 张微型合约",
      "Elite 计划",
      "$50K 账户：4 张合约 | 最多 4 张迷你合约或 40 张微型合约",
      "$100K 账户：8 张合约 | 最多 8 张迷你合约或 80 张微型合约",
      "$150K 账户：12 张合约 | 最多 12 张迷你合约或 120 张微型合约",
      "即时入金计划与即时定制",
      "$25K 账户：2 张合约 | 最多 2 张迷你合约或 20 张微型合约",
      "$50K 账户：4 张合约 | 最多 4 张迷你合约或 40 张微型合约",
      "$100K 账户：8 张合约 | 最多 8 张迷你合约或 80 张微型合约"
    ]
  },
  "goat-funded-futures": {
    "aiSummaryZh": "Goat Funded Futures 成立于2024年11月，总部位于香港，提供期货交易项目，分为一阶段和即时入金两种类型。支持 TradingView、Quantower、Tradovate、Volumetrica Trading、NinjaTrader、ATAS Orderflow Trading、Deepmap 和 Deepcharts 等交易平台。客户评分 4.3/5（共11条评价）。",
    "offerDescriptionZh": "立减 50% + 限时特价",
    "consistencyRulesZh": [
      {
        "program": "EOD Accounts",
        "rule": "单日盈利不得超过评估期总盈利的 50%，签约后不超过 30%"
      },
      {
        "program": "Instant",
        "rule": "单日盈利不得超过总盈利的 20%（即时入金无评估期）"
      },
      {
        "program": "Sprint",
        "rule": "签约后单日盈利不超过总盈利的 30%（评估期无限制）。评估期需达成 50% 一致性评分，模拟签约无此要求"
      }
    ],
    "leverageZh": [
      "EOD",
      "$50K: 5 份迷你 / 50 份微型合约",
      "$100K: 9 份迷你 / 90 份微型合约",
      "$150K: 12 份迷你 / 120 份微型合约",
      "Sprint",
      "$25K: 3 份迷你 / 30 份微型合约",
      "$50K: 5 份迷你 / 50 份微型合约",
      "$100K: 7 份迷你 / 70 份微型合约",
      "Instant",
      "$25K: 3 份迷你 / 30 份微型合约",
      "$50K: 4 份迷你 / 40 份微型合约",
      "$75K: 5 份迷你 / 50 份微型合约"
    ]
  },
  "hola-prime-futures": {
    "aiSummaryZh": "Hola Prime Futures 是一家2025年6月成立于香港的期货自营公司，提供期货交易产品，开设即时入金和一阶段两种签约模式。支持Tradovate、Dx Futures和NinjaTrader等多个交易平台。用户评分5/5（基于1条评价），为交易者提供多平台期货交易解决方案。",
    "offerDescriptionZh": "启动优惠 立减50%",
    "consistencyRulesZh": [],
    "leverageZh": [
      "最大敞口限制",
      "一阶段Prime挑战赛",
      "$25,000账户：最多1手迷你合约或10手微型合约",
      "$50,000账户：最多3手迷你合约或30手微型合约",
      "$100,000账户：最多7手迷你合约或70手微型合约",
      "$150,000账户：最多10手迷你合约或100手微型合约",
      "直通账户",
      "$25,000账户：最多1手迷你合约或10手微型合约",
      "$50,000账户：最多3手迷你合约或30手微型合约",
      "$100,000账户：最多6手迷你合约或60手微型合约",
      "$150,000账户：最多9手迷你合约或90手微型合约"
    ]
  },
  "lucid-trading": {
    "aiSummaryZh": "Lucid Trading 成立于 2025 年 3 月，是一家美国自营公司，专注期货交易。提供即时入金和一阶段两种账户类型，支持 Bookmap、Sierra Chart、MotiveWave、Jigsaw Daytradr、MultiCharts、Quantower、R Trader Pro、Tradovate、NinjaTrader、ATAS Orderflow Trading 和 Tradesea TradingView 等平台。客户评分 4.6/5（39 条评价）。",
    "offerDescriptionZh": "Flex 和 Pro 账户 40% 折扣（限 5 次使用）",
    "consistencyRulesZh": [
      {
        "program": "Rapid",
        "rule": "挑战赛阶段单日盈利不超过总盈利的 50%；签约后无一致性要求"
      },
      {
        "program": "Pro",
        "rule": "挑战赛阶段单日盈利不超过总盈利的 50%；签约后无一致性要求（$50K 附加账户的挑战赛和签约阶段无一致性限制）"
      },
      {
        "program": "Flex",
        "rule": "挑战赛阶段单日盈利不超过总盈利的 50%；签约后无一致性要求"
      },
      {
        "program": "Builder",
        "rule": "签约阶段单日盈利不超过总盈利的 50%；挑战赛无一致性要求"
      }
    ],
    "leverageZh": [
      "最大合约规模",
      "$25k - 2 手迷你合约或 20 手微型合约",
      "$50k - 4 手迷你合约或 40 手微型合约",
      "$100k - 6 手迷你合约或 60 手微型合约",
      "$150k - 10 手迷你合约或 100 手微型合约"
    ]
  },
  "my-funded-futures": {
    "aiSummaryZh": "My Funded Futures 成立于 2023 年 11 月，总部位于美国，提供期货交易一阶段挑战赛。账户规模从 $50,000 至 $150,000。支持 TradingView、Quantower、Volbook、Volsys、Tradovate、Volumetrica Trading、NinjaTrader 和 ATAS Orderflow Trading 等交易平台。交易品种覆盖 CME、CBOT、COMEX、NYMEX 等交易所的期货合约，并按资产类别提供杠杆：外汇 1:100、指数 1:20、贵金属（黄金 1:80）等。",
    "offerDescriptionZh": "所有挑战赛账户享 50% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Rapid",
        "rule": "挑战赛阶段单日利润不得超过总利润的 50%。签约阶段无一致性要求。"
      },
      {
        "program": "Pro",
        "rule": "挑战赛阶段单日利润不得超过总利润的 50%。签约阶段无一致性要求。（$50K 附加账户的挑战赛和签约阶段无一致性要求）"
      },
      {
        "program": "Flex",
        "rule": "挑战赛阶段单日利润不得超过总利润的 50%。签约阶段无一致性要求。"
      },
      {
        "program": "Builder",
        "rule": "签约阶段单日利润不得超过总利润的 50%。挑战赛阶段无一致性要求。"
      }
    ],
    "leverageZh": [
      "各账户规模最大合约数限制",
      "Flex",
      "$25,000 账户：最多 3 份迷你合约或 30 份微型合约",
      "$50,000 账户：最多 5 份迷你合约或 50 份微型合约",
      "Pro",
      "$50,000 账户：最多 3 份迷你合约或 30 份微型合约",
      "$100,000 账户：最多 6 份迷你合约或 60 份微型合约",
      "$150,000 账户：最多 9 份迷你合约或 90 份微型合约",
      "Rapid",
      "$25,000 账户：最多 3 份迷你合约或 30 份微型合约",
      "$50,000 账户：最多 5 份迷你合约或 50 份微型合约",
      "$100,000 账户：最多 10 份迷你合约或 100 份微型合约"
    ]
  },
  "take-profit-trader": {
    "aiSummaryZh": "Take Profit Trader 提供挑战赛和签约账户，支持多种杠杆档位。现推出全部挑战赛账户 50% 折扣优惠。平台根据账户规模灵活配置合约数量，从 $25K 的 3 手起至 $150K 的 15 手，满足不同交易风格需求。",
    "offerDescriptionZh": "全部挑战赛账户享 50% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Combine",
        "rule": "单日利润不得超过总利润的 50%（挑战赛）"
      },
      {
        "program": "Express Funded Standard Path",
        "rule": "无一致性要求（签约账户）"
      },
      {
        "program": "Express Funded Consistency Path",
        "rule": "单日利润不得超过总利润的 40%（签约账户）"
      }
    ],
    "leverageZh": [
      "杠杆：按账户规模分配最大合约数",
      "$25K：3 手合约 / 30 微型合约",
      "$50K：6 手合约 / 60 微型合约",
      "$75K：9 手合约 / 90 微型合约",
      "$100K：12 手合约 / 120 微型合约",
      "$150K：15 手合约 / 150 微型合约"
    ]
  },
  "the-trading-pit-futures": {
    "aiSummaryZh": "The Trading Pit Futures 成立于2022年10月，总部位于列支敦士登。公司支持期货、外汇、指数、商品、加密货币及股票交易，提供一阶段和两阶段挑战赛项目。账户规模从 $10,000 到 $100,000，兼容 TradingView、Quantower、R Trader Pro、Volsys、Tradovate、NinjaTrader、ATAS、MT4、MT5 及 Bookmap 等多个交易平台。",
    "offerDescriptionZh": "所有挑战赛账户享受 30% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Combine",
        "rule": "单日盈利不得超过总盈利的 50%（挑战赛）"
      },
      {
        "program": "Express Funded Standard Path",
        "rule": "无一致性要求（签约）"
      },
      {
        "program": "Express Funded Consistency Path",
        "rule": "单日盈利不得超过总盈利的 40%（签约）"
      }
    ],
    "leverageZh": [
      "杠杆：按账户规模允许的最大合约数",
      "The Trading Pit - Futures Prime",
      "$50K 账户：5 手合约 / 50 迷你手",
      "$100K 账户：10 手合约 / 100 迷你手",
      "$150K 账户：15 手合约 / 150 迷你手"
    ]
  },
  "top-one-futures": {
    "aiSummaryZh": "Top One Futures 成立于 2025 年 4 月，总部位于美国，专注于期货交易。公司提供一阶段入金计划，支持 TradingView、Tradovate 和 NinjaTrader 平台。平台评分 4.7 分（满分 5 分，基于 72 条评价），以简洁高效的期货交易解决方案见长。",
    "offerDescriptionZh": "所有挑战赛账户立减 60% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Combine",
        "rule": "单日盈利不得超过总盈利的 50%。（挑战赛）"
      },
      {
        "program": "Express Funded Standard Path",
        "rule": "无一致性要求。（签约账户）"
      },
      {
        "program": "Express Funded Consistency Path",
        "rule": "单日盈利不得超过总盈利的 40%。（签约账户）"
      }
    ],
    "leverageZh": [
      "$25,000 账户 – 最多 1 份迷你合约（或 10 份微型合约）",
      "$50,000 账户 – 最多 3 份迷你合约（或 30 份微型合约）",
      "$100,000 账户 – 最多 5 份迷你合约（或 50 份微型合约）",
      "$150,000 账户 – 最多 7 份迷你合约（或 70 份微型合约）"
    ]
  },
  "topstep": {
    "aiSummaryZh": "Topstep 是一家成立于 2012 年 1 月的美国自营公司，提供一阶段期货交易计划。账户规模从 $50K 到 $150K，支持 TopstepX、NinjaTrader、Quantower、T4、R Trader Pro 等多个交易平台，覆盖 CME 股指期货（ES、MES、NQ 等）及其他主流合约。",
    "offerDescriptionZh": "",
    "consistencyRulesZh": [
      {
        "program": "Combine",
        "rule": "交易员单日盈利不得超过总盈利的 50%（挑战赛）"
      },
      {
        "program": "Express Funded Standard Path",
        "rule": "无一致性要求（签约账户）"
      },
      {
        "program": "Express Funded Consistency Path",
        "rule": "交易员单日盈利不得超过总盈利的 40%（签约账户）"
      }
    ],
    "leverageZh": [
      "杠杆 = 根据账户规模允许的最大合约数"
    ]
  },
  "tradeday": {
    "aiSummaryZh": "TradeDay 是一家美国自营公司，成立于 2020 年 1 月，专注期货交易。提供一阶段签约项目，账户规模从 $10,000 到 $250,000。支持 TradingView、Jigsaw Daytradr、Tradovate、TradeDayX 和 NinjaTrader 等交易平台，可交易 CME、CBOT、NYMEX 和 COMEX 等交易所的期货。用户评分 4.8/5（11 条评价）。",
    "offerDescriptionZh": "挑战赛账户全场 30% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Consistency Rule of 35%",
        "rule": "适用于所有 Growth Sim 签约账户，单个交易日的最高盈利不得超过总盈利的 35%"
      },
      {
        "program": "Consistency Rule of 20%",
        "rule": "适用于所有 Lightning Funded 账户，单个交易日最高盈利第 1 次出金不超 20%，第 2 次不超 25%，第 3 次及以后不超 30%"
      },
      {
        "program": "Consistency Rule of 40%",
        "rule": "适用于所有 Select 账户，评估阶段内单个交易日的最高盈利不得超过 40%"
      }
    ],
    "leverageZh": [
      "各账户档位在所有计划下的最大合约规模",
      "$50,000 账户：最多 5 手迷你合约或 50 手微型合约",
      "$100,000 账户：最多 10 手迷你合约或 100 手微型合约",
      "$150,000 账户：最多 15 手迷你合约或 150 手微型合约"
    ]
  },
  "tradeify": {
    "aiSummaryZh": "Tradeify成立于2024年6月，总部位于美国。专注期货交易，提供一阶段和即时入金两种程序。支持Sierra Chart、TradingView、Quantower、Rithmic、Tradovate、WealthCharts、NinjaTrader等多个交易平台。公司在155条用户评价中获得4.7/5的高分评价，是一家以期货为核心的自营交易公司。",
    "offerDescriptionZh": "所有挑战赛账户享40% 折扣",
    "consistencyRulesZh": [
      {
        "program": "Consistency Rule of 35%",
        "rule": "适用于所有Growth Sim签约账户，单个交易日最大利润不得超过总利润的35%"
      },
      {
        "program": "Consistency Rule of 20%",
        "rule": "适用于所有Lightning签约账户，单个交易日最大利润不得超过：第一次出金20%、第二次出金25%、第三次及之后出金30%"
      },
      {
        "program": "Consistency Rule of 40%",
        "rule": "适用于所有Select账户，评估阶段内单个交易日最大利润不得超过40%"
      }
    ],
    "leverageZh": [
      "Growth、Select及Lightning签约账户杠杆配置：",
      "$25k账户：最多1手合约（10微型合约）",
      "$50k账户：最多4手合约（40微型合约）",
      "$100k账户：最多8手合约（80微型合约）",
      "$150k账户：最多12手合约（120微型合约）"
    ]
  },
  "traders-launch": {
    "aiSummaryZh": "Traders Launch 成立于 2023 年 8 月，是一家美国自营公司。提供期货交易和一阶段挑战赛，账户规模从 $5,000 到 $100,000。支持 Quantower、Volumetrica Trading、IBKR 和 NinjaTrader 平台。可交易约 300 只流动性股票、ETF 及主要指数产品（SPX、NDX、US30、GLD 等）。评分 4.6/5（基于 19 条评价）。",
    "offerDescriptionZh": "所有挑战赛账户享 15% 折扣",
    "consistencyRulesZh": [],
    "leverageZh": [
      "杠杆：每账户最大合约数量",
      "纽约时段",
      "$100K - 5 Micro 合约",
      "$200K - 1 Mini 或 10 Micro 合约",
      "$300K - 2 Mini 或 20 Micro 合约",
      "全时段",
      "$100K - 2 Mini 或 20 Micro 合约",
      "$200K - 4 Mini 或 40 Micro 合约",
      "$300K - 6 Mini 或 60 Micro 合约"
    ]
  }
};

export function findFirmZh(slug: string): FirmZh | undefined {
  return FIRMS_ZH[slug];
}
